name: Auto-Merge & Reporting

on:
  pull_request:
    types: [closed]

jobs:
  merge-and-report:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Get changed files in the PR
      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v44

      # Create deployment report file
      - name: Generate Deployment Report
        run: |
          mkdir -p reports
          {
            echo "**Version**: ${{ github.run_number }}"
            echo "**Merged By**: ${{ github.actor }}"
            echo "**Date**: ${{ github.event.pull_request.merged_at }}"
            echo "**Changed Files:**"
            for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              echo "- $file"
            done
          } > reports/deployment-${{ github.run_number }}.md

      # Commit the report to the repo
      - name: Commit and Push Report
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add reports/
          git commit -m "Add deployment report ${{ github.run_number }}"
          git push
