name: Auto-Merge Report

on:
  pull_request:
    types: [closed]
    branches:
      - main # Change this if your default branch is different
jobs:
  merge-and-report:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Generate Unique Report Filename
        run: echo "REPORT_FILE=reports/deployment-$(date +'%Y%m%d%H%M%S').md" >> $GITHUB_ENV

      - name: Create Deployment Report
        run: |
          mkdir -p reports
          {
            echo "**Version**: ${{ github.run_number }}"
            echo "**Merged By**: ${{ github.actor }}"
            echo "**Date**: ${{ github.event.pull_request.merged_at }}"
            echo "**Changed Files:**"
            for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              echo "- $file"
            done
          } > $REPORT_FILE

      - name: Commit and Push Report
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
          git add $REPORT_FILE
          git commit -m "Add deployment report for #${{ github.event.pull_request.number }}"
          git push
