name: Auto-Merge Report

on:
  pull_request:
    types: [closed]
    branches:
      - main # Change this if your default branch is different
jobs:
  generate-report:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate report
        run: |
          mkdir -p reports
          echo "### Deployment Report - #${{ github.run_number }}" > reports/deployment-${{ github.run_number }}.md
          echo "**Merged by**: ${{ github.actor }}" >> reports/deployment-${{ github.run_number }}.md
          echo "**Date**: $(date)" >> reports/deployment-${{ github.run_number }}.md
          echo "**Changed Files:**" >> reports/deployment-${{ github.run_number }}.md
          echo "${{ steps.changed-files.outputs.all_changed_files }}" >> reports/deployment-${{ github.run_number }}.md

      - name: Commit and push report
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add reports/
          git commit -m "Add deployment report for run #${{ github.run_number }}"
          git push
