name: Auto-Merge & Reporting

on:
  pull_request:
    branches: [feature/auto-merge-workflow]
    types: [closed]

jobs:
  merge-and-report:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      # Track changed files
      - name: Identify Changed Files
        uses: BuddhikaGeasman/which-files-changed@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr-comment: "false"

      # Generate Report
      - name: Create Change Report
        uses: michaelhenry/create-report@v2
        with:
          title: "Deployment Report - ${{ github.run_number }}"
          path: reports/deployment-${{ github.run_number }}.md
          format: markdown
        env:
          REPORT_CONTENT: |
            **Version**: ${{ github.run_number }}
            **Merged By**: ${{ github.actor }}
            **Date**: ${{ github.event.pull_request.merged_at }}
            **Changed Files**:
            ${{ steps.changed-files.outputs.files }}

      # Commit report
      - name: Commit Report
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add reports/
          git commit -m "Add deployment report ${{ github.run_number }}"
          git push
